# 基础算术运算 (Element-wise)

In [2]:
import torch
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# 逐元素相加
print("== a+b ==")
print(a + b)
print(torch.add(a, b))

# 逐元素相乘
print("== a*b ==")
print(a * b)
print(torch.mul(a, b))

print("== a-b ==")
print(a - b)
print(torch.sub(a, b))

print("== a/b ==")
print(a / b)
print(torch.div(a, b))

print("== a**b ==")
print(b ** a)
print(torch.pow(b, a))


== a+b ==
tensor([5, 7, 9])
tensor([5, 7, 9])
== a*b ==
tensor([ 4, 10, 18])
tensor([ 4, 10, 18])
== a-b ==
tensor([-3, -3, -3])
tensor([-3, -3, -3])
== a/b ==
tensor([0.2500, 0.4000, 0.5000])
tensor([0.2500, 0.4000, 0.5000])
== a**b ==
tensor([  4,  25, 216])
tensor([  4,  25, 216])
